# Generated by Django 6.0.5 on 2026-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_directing_rating_review_story_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_tag',
            field=models.CharField(blank=True, choices=[('mind_blown', '🤯 반전 대박'), ('popcorn', '🍿 가볍게 보기 좋음'), ('tear_jerk', '😭 눈물 버튼'), ('masterpiece', '✨ 인생 명작'), ('time_killer', '⏱️ 시간 순삭')], max_length=20, null=True),
        ),
    ]
